doctrine:
    dbal:
        dbname: "beery"
        url: '%env(DATABASE_URL)%'
        types:
            abv: App\Infrastructure\Doctrine\Type\AbvType
            name: App\Infrastructure\Doctrine\Type\NameType
            email: App\Infrastructure\Doctrine\Type\EmailType
            password: App\Infrastructure\Doctrine\Type\PasswordType
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            Domain:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Infrastructure/Resources/config/doctrine/domain'
                prefix: 'App\Domain\Model'
            View:
                type: 'xml'
                dir: '%kernel.root_dir%/Resources/config/doctrine/view'
                prefix: 'App\Infrastructure\View'
                is_bundle: false
