doctrine:
    dbal:
        types:
            # More details about this usage of this type instead of regular uuid can be found here https://www.percona.com/blog/2014/12/19/store-uuid-optimized-way/
            uuid_binary_ordered_time: Ramsey\Uuid\Doctrine\UuidBinaryOrderedTimeType
        mapping_types:
            uuid_binary_ordered_time: binary
