language: php

php:
    - 7.1

env:
    global:
        - DATABASE_URL="mysql://root@127.0.0.1:3306/symfony?charset=utf8mb4&serverVersion=5.7"

cache:
    directories:
        - vendor

before_install:
    - phpenv config-rm xdebug.ini || true
    - composer self-update

install:
    - composer install
    - bin/console doctrine:database:create --env test
    - bin/console doctrine:schema:create --env test

script:
    - composer validate --strict
    - vendor/bin/behat --strict -v
    - vendor/bin/phpspec run
