language: php

php:
    - 7.1

services:
  - neo4j

cache:
    directories:
        - vendor

before_install:
    - source .test.env

    - phpenv config-rm xdebug.ini || true

install:
    - composer install --prefer-dist
    - bin/console doctrine:database:create --env test
    - bin/console doctrine:schema:create --env test

    - mkdir var/jwt
    - openssl genrsa -out var/jwt/private.pem 4096 -passout env:JWT_PASSPHRAS
    - openssl rsa -pubout -in var/jwt/private.pem -out var/jwt/public.pem

script:
    - composer validate --strict
    - composer analyse
    - vendor/bin/phpspec run -fpretty --ansi
    - vendor/bin/behat --strict --colors
