berry_add_connoisseur:
    path: '/register'
    methods: ['POST']
    defaults:
        _controller: 'app.infrastructure.controller.register_connoisseur_action'

berry_add_beer:
    path: '/beers'
    methods: ['POST']
    defaults:
        _controller: 'app.infrastructure.controller.add_beer_action'

berry_browse_beers:
    path: '/beers'
    methods: ['GET']
    defaults:
        _controller: 'app.infrastructure.controller.browse_beers_action'

api_login_check:
    path: '/login_check'
