berry_add_connoisseur:
    path: '/register'
    methods: ['POST']
    defaults:
        _controller: 'App\Infrastructure\Controller\RegisterConnoisseurAction'

berry_add_beer:
    path: '/beers'
    methods: ['POST']
    defaults:
        _controller: 'App\Infrastructure\Controller\AddBeerAction'

berry_browse_beers:
    path: '/beers'
    methods: ['GET']
    defaults:
        _controller: 'App\Infrastructure\Controller\BrowseBeersAction'

api_login_check:
    path: '/login_check'
