parameters:
    locale: 'en'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Application\:
        public: true
        resource: '../src/Application/'
        exclude: '../src/Application/Command'

    App\Application\CommandHandler\:
        resource: '../src/Application/CommandHandler'
        public: true
        lazy: true
        tags:
            - { name: "prooph_service_bus.app_command_bus.route_target", message_detection: true }

    App\Infrastructure\Controller\:
        resource: '../src/Infrastructure/Controller'
        tags: ['controller.service_arguments']

    Prooph\ServiceBus\CommandBus: '@prooph_service_bus.app_command_bus'
    Prooph\ServiceBus\EventBus: '@prooph_service_bus.app_event_bus'
